package org.surreal.lobster.sharedcore.presenter.rankRateStrategies;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import org.surreal.lobster.sharedcore.databroker.DataBrokerCallback;
import org.surreal.lobster.sharedcore.view.OptionListItem;

public class JobTitleStrategy extends BaseRankRateEntryStrategy {

	private static final String NAF = "E";
	private static final String WG = "D";
	private static final String WM = "F";
	private static final String DEMONSTRATION_PROJECT = "C";
	private static final String SES = "B";
	private static final String GS = "A";
	private final HashMap<String, List<OptionListItem>> cache = new HashMap<String, List<OptionListItem>>();

	@Override
	public boolean shouldShow(String... values) {
		return isCivilian(values) && values.length > 2 && !values[2].trim().isEmpty();
	}
	
	@Override
	public void getItems(DataBrokerCallback<List<OptionListItem>> callback, String... values) {
		String civilianSeries = values[2];
		// Because this is such a cost to performance, we're cacheing the results
		// and verifying that we really need to do this by checking to make sure
		// it's a civilian we're dealing with here.
		if (civilianSeries != null && isCivilian(values)) {
			if (cache.get(civilianSeries) == null) {
				cache.put(civilianSeries, genList(civilianSeries));
			}
		}
		callback.onSuccess(deselectAll(cache.get(civilianSeries)));
	}

	private List<OptionListItem> genList(String civilianSeries) {
		List<OptionListItem> list = new ArrayList<OptionListItem>();
		list.add(genItem("    "));
		if (GS.equals(civilianSeries) || SES.equals(civilianSeries) || DEMONSTRATION_PROJECT.equals(civilianSeries)) {
			loadGS(list);
		} else if (WM.equals(civilianSeries)) {
			loadWM(list);
		} else if (WG.equals(civilianSeries)) {
			loadWG(list);
		} else if (NAF.equals(civilianSeries)) {
			loadNaf(list);
		}
		return list;
	}

	private void loadNaf(List<OptionListItem> list) {
		list.add(genItem("510 ","ACCOUNTING CLERK"));
		list.add(genItem("525 ","ACCOUNTING TECH"));
		list.add(genItem("525 ","ACCT. TECH/BOOKKEEPER"));
		list.add(genItem("1101","ASSISTANT CLUB MANAGER"));
		list.add(genItem("1640","ASST. FACILITY MANAGER"));
		list.add(genItem("5823","AUTO MECHANIC"));
		list.add(genItem("5703","AUTO MECHANIC SPYR"));
		list.add(genItem("5823","AUTOMOTIVE MKR (HELPER)"));
		list.add(genItem("7405","BARTENDER"));
		list.add(genItem("4742","BOWL EQUIP MECHANIC"));
		list.add(genItem("1101","BOWLING CNTR MGR."));
		list.add(genItem("4742","BOWLING EQUIP RPR HLPR"));
		list.add(genItem("1101","CAFETERIA MANAGER"));
		list.add(genItem("530 ","CASH CLERK"));
		list.add(genItem("530 ","CASHIER"));
		list.add(genItem("2091","CASHIER/CHECKER"));
		list.add(genItem("530 ","CASHIER/CLERK"));
		list.add(genItem("1101","CATERING COORDINATOR"));
		list.add(genItem("1701","CDC DIRECTOR"));
		list.add(genItem("1701","CDH DIRECTOR"));
		list.add(genItem("525 ","CENTRAL CASHIER"));
		list.add(genItem("1701","CHILD AND YOUTH SCHOOL LIAISON OFFICER"));
		list.add(genItem("322 ","CLERK TYPIST"));
		list.add(genItem("1101","CLUB MANAGER"));
		list.add(genItem("1102","CONTRACT SPECIALIST"));
		list.add(genItem("7404","COOK"));
		list.add(genItem("7404","COOK FRMN"));
		list.add(genItem("302 ","COURIER"));
		list.add(genItem("3566","CUSTODIAL SPVR"));
		list.add(genItem("3566","CUSTODIAL WKR"));
		list.add(genItem("3566","CUSTODIAL WKR (COM AREA)"));
		list.add(genItem("3566","CUSTODIAL WKR (ROOMS)"));
		list.add(genItem("3566","CUSTODIAL WKR LDR"));
		list.add(genItem("1702","EDUCATION AID(C CARE)"));
		list.add(genItem("1702","EDUCATION AIDE (PRE-K)"));
		list.add(genItem("1702","EDUCATION TECH(C CARE)"));
		list.add(genItem("2805","ELECTRICIAN"));
		list.add(genItem("8610","ENGINE REPAIRER"));
		list.add(genItem("1640","FACILITIES AND MAINTENANCE MGR"));
		list.add(genItem("1101","FHC FOOD PGRM MGR."));
		list.add(genItem("30","FITNESS SPECIALIST"));
		list.add(genItem("7408","FOOD SERVICE WKR"));
		list.add(genItem("7408","FOOD SERVICE WKR (SOC)"));
		list.add(genItem("7408","FOOD SERVICE WKR FRMN"));
		list.add(genItem("7408","FOOD SERVICE WKR LDR"));
		list.add(genItem("7408","FOOD SERVICE WKR SUPV"));
		list.add(genItem("5003","GARDENER"));
		list.add(genItem("5003","GARDENER/TRACTOR OPR LDR"));
		list.add(genItem("5008","GARDENER (TRACTOR OPR)"));
		list.add(genItem("5008","GARDENER (TRCTR OPR) SPVR"));
		list.add(genItem("203 ","GENERAL CLERK"));
		list.add(genItem("303 ","GENERAL CLERK"));
		list.add(genItem("1601","GOLF ASST SUPER"));
		list.add(genItem("1101","GOLF COURSE ASST MGR."));
		list.add(genItem("1101","GOLF COURSE EQUIP MGR."));
		list.add(genItem("1101","GOLF COURSE MGR."));
		list.add(genItem("1601","GOLF SUPERINTENDENT"));
		list.add(genItem("1020","GRAPHIC ARTIST"));
		list.add(genItem("1173","HOST/CASHIER"));
		list.add(genItem("65","HOUSING ASST (SECURITY)"));
		list.add(genItem("1173","HOUSING MGMT SPEC"));
		list.add(genItem("189 ","LABORER"));
		list.add(genItem("3502","LABORER"));
		list.add(genItem("3502","LABORER (BOWLING MAINT)"));
		list.add(genItem("4749","LABORER (BOWLING MAINT)"));
		list.add(genItem("3502","LABORER (RECYCLING)"));
		list.add(genItem("3502","LABORER (RECYL/HAZD)"));
		list.add(genItem("1702","LEAD EDUCATION TECH"));
		list.add(genItem("203 ","LEAD PAY/BENEFITS TECH"));
		list.add(genItem("0189","LIFEGUARD"));
		list.add(genItem("0189","LIFEGUARD INSTRUCTOR"));
		list.add(genItem("4749","MAINTENANCE MECHANIC"));
		list.add(genItem("4749","MAINTENANCE MECHANIC SUPV"));
		list.add(genItem("4749","MAINTENANCE WKR"));
		list.add(genItem("4848","MECH PARTS ASSEMBLER"));
		list.add(genItem("303 ","MISC CLERK/ASST"));
		list.add(genItem("4749","MOTOR VEHICLE OPERATOR"));
		list.add(genItem("5703","MOTOR VEHICLE OPR"));
		list.add(genItem("1101","MWR DIRECTOR"));
		list.add(genItem("","NAF NEC"));
		list.add(genItem("325 ","OFFICE AUTOMATION CLK"));
		list.add(genItem("326 ","OFFICE AUTOMATION CLK"));
		list.add(genItem("303 ","OPERATIONS ASST (VET)"));
		list.add(genItem("1101","OPERATIONS MANAGER"));
		list.add(genItem("1101","OUTDR EQUIP MGR."));
		list.add(genItem("203 ","PAY/BENEFITS TECH"));
		list.add(genItem("201 ","PERSONNEL SPECIALIST"));
		list.add(genItem("203 ","PERSONNEL TECH"));
		list.add(genItem("5206","POOL OPERATOR"));
		list.add(genItem("1710","PRE-K TEACHER"));
		list.add(genItem("1106","PROCUREMENT CLK"));
		list.add(genItem("301 ","PROGRAM ASSISTANT"));
		list.add(genItem("189 ","REC AID"));
		list.add(genItem("189 ","REC AID (AUTO/HOBBY)"));
		list.add(genItem("189 ","REC AID (B0WL CNTR CLK)"));
		list.add(genItem("189 ","REC AID (BAG STORAGE)"));
		list.add(genItem("189 ","REC AID (CAMPING)"));
		list.add(genItem("189 ","REC AID (CRAFT/HOBBY)"));
		list.add(genItem("189 ","REC AID (DOCK ATTND)"));
		list.add(genItem("189 ","REC AID (FITNESS)"));
		list.add(genItem("189 ","REC AID (GEAR ISSUE)"));
		list.add(genItem("189 ","REC ASST (HEAD GUARD)"));
		list.add(genItem("189 ","REC ASST (HOUSING)"));
		list.add(genItem("189 ","REC ASST (ITT)"));
		list.add(genItem("189 ","REC ASST (LIBERTY)"));
		list.add(genItem("189 ","REC ASST (OUTDOOR REC)"));
		list.add(genItem("189 ","REC ASST (WIND/SEA)"));
		list.add(genItem("189 ","REC ASST (WSI)"));
		list.add(genItem("189 ","REC ASST (Y/YA)"));
		list.add(genItem("304 ","RECEPTIONIST"));
		list.add(genItem("188 ","REC SPEC (FLECT REC"));
		list.add(genItem("188 ","REC SPEC (SAILING)"));
		list.add(genItem("188 ","REC SPECIALIST"));
		list.add(genItem("1101","RECYCLING PRGM COOR"));
		list.add(genItem("1101","RECYCLING PRGM MGR."));
		list.add(genItem("1101","RECYCLING PRGM SPEC"));
		list.add(genItem("2091","SALES CLERK"));
		list.add(genItem("1704","SCHOOL LIAISON OFFICER"));
		list.add(genItem("1101","SNACK BAR OPERATIONS MGR."));
		list.add(genItem("2091","SNACK BAR OPERATOR"));
		list.add(genItem("1101","SPONSORSHIP COORDINATOR"));
		list.add(genItem("510 ","SPVY BUDGET OFFICER"));
		list.add(genItem("201 ","SPVY PERS MGMT SPEC"));
		list.add(genItem("189 ","SPVY REC ASST"));
		list.add(genItem("189 ","SPVY REC ASST (BOWLING)"));
		list.add(genItem("189 ","SPVY REC ASST (BWL N MGR.)"));
		list.add(genItem("2005","SUPPLY CLERK"));
		list.add(genItem("2005","SUPPLY TECH"));
		list.add(genItem("1101","SUPPORT SERVICES MGR"));
		list.add(genItem("188 ","SUPV REC SPECIALIST"));
		list.add(genItem("6904","TOOL AND PARTS ATTENDANT"));
		list.add(genItem("5704","TRACTOR OPERATOR"));
		list.add(genItem("5705","TRACTOR OPERATOR"));
		list.add(genItem("5704","TRACTOR OPR/LAB0RER LDR"));
		list.add(genItem("1701","TRAINING & CURRICULUM SPEC"));
		list.add(genItem("701 ","VET MEDICAL OFFICER"));
		list.add(genItem("3566","WAITER"));
		list.add(genItem("7420","WAITER"));
		list.add(genItem("7420","WAITER LEADER"));
		list.add(genItem("6907","WAREHOUSE WORKER"));
	}

	private void loadWG(List<OptionListItem> list) {
		list.add(genItem("5306","AIR CONDITIONING EQUIPMENT MECHANIC"));
		list.add(genItem("5415","AIR CONDITIONING EQUIPMENT OPERATING"));
		list.add(genItem("8862","AIRCRAFT ATTENDING"));
		list.add(genItem("2892","AIRCRAFT ELECTRICIAN"));
		list.add(genItem("8602","AIRCRAFT ENGINE MECHANIC"));
		list.add(genItem("6968","AIRCRAFT FREIGHT LOADING"));
		list.add(genItem("5301","AIRCRAFT LAUNCHING & ARRESTING DEVICES MECHANIC"));
		list.add(genItem("8852","AIRCRAFT MECHANIC"));
		list.add(genItem("8840","AIRCRAFT MECHANICAL PARTS REPAIRING"));
		list.add(genItem("6652","AIRCRAFT ORDNANCE SYSTEMS MECHANIC"));
		list.add(genItem("8268","AIRCRAFT PNEUDRAULIC SYSTEMS MECHANIC"));
		list.add(genItem("8810","AIRCRAFT PROPELLAR MECHANIC"));
		list.add(genItem("4818","AIRCRAFT SURVIVAL AND FLIGHT EQUIPMENT REPAIRING"));
		list.add(genItem("5485","AIRCRAFT WEIGHT AND BALANCE OPERATING"));
		list.add(genItem("5767","AIRFIELD CLEARING EQUIPMENT OPERATING"));
		list.add(genItem("3819","AIRFRAME JIG FITTING"));
		list.add(genItem("8882","AIRFRAME TEST OPERATING"));
		list.add(genItem("5048","ANIMAL CARETAKING"));
		list.add(genItem("6605","ARTILLERY REPAIRING"));
		list.add(genItem("6606","ARTILLERY TESTING"));
		list.add(genItem("3653","ASPHALT WORKING"));
		list.add(genItem("5823","AUTOMOTIVE MECHANIC"));
		list.add(genItem("7402","BAKING"));
		list.add(genItem("4445","BANK NOTE DESIGNING"));
		list.add(genItem("4446","BANK NOTE ENGRAVING"));
		list.add(genItem("7603","BARBERING"));
		list.add(genItem("7405","BARTENDING"));
		list.add(genItem("3725","BATTERY REPAIRING"));
		list.add(genItem("4850","BEARING RECONDITIONING"));
		list.add(genItem("7641","BEAUTICIAN"));
		list.add(genItem("4402","BINDERY WORKING"));
		list.add(genItem("4602","BLOCKING AND BRACING"));
		list.add(genItem("4717","BOAT BUILDING AND REPAIRING"));
		list.add(genItem("3808","BOILERMAKING"));
		list.add(genItem("5402","BOILER PLANT OPERATING"));
		list.add(genItem("4441","BOOKBINDING"));
		list.add(genItem("4819","BOWLING EQUIPMENT REPAIRING"));
		list.add(genItem("5736","BRAKING SWITCHING AND CONDUCTING"));
		list.add(genItem("3940","BROADCASTING EQUIPMENT OPERATING"));
		list.add(genItem("3119","BROOM AND BRUSH MAKING"));
		list.add(genItem("3727","BUFFING AND POLISHING"));
		list.add(genItem("6941","BULK MONEY HANDLING"));
		list.add(genItem("4607","CARPENTRY"));
		list.add(genItem("5435","CARTON/BAG MAKING MACHINE OPERATING"));
		list.add(genItem("3602","CEMENT FINISHING"));
		list.add(genItem("4754","CEMETERY CARETAKING"));
		list.add(genItem("4807","CHEMICAL EQUIPMENT REPAIRING"));
		list.add(genItem("5427","CHEMICAL PLANT OPERATING"));
		list.add(genItem("3736","CIRCUIT BOARD MAKING"));
		list.add(genItem("6903","COAL HANDLING"));
		list.add(genItem("3513","COIN/CURRENCY CHECKING"));
		list.add(genItem("2508","COMMUNICATIONS LINE INSTALLING AND REPAIRING"));
		list.add(genItem("7404","COOKING"));
		list.add(genItem("5484","COUNTING MACHINE OPERATING"));
		list.add(genItem("5725","CRANE OPERATING"));
		list.add(genItem("4808","CUSTODIAL EQUIPMENT SERVICING"));
		list.add(genItem("3566","CUSTODIAL WORKING"));
		list.add(genItem("5034","DAIRY FARMING"));
		list.add(genItem("5788","DECKHAND"));
		list.add(genItem("3428","DIE SINKING"));
		list.add(genItem("4855","DOMESTIC APPLIANCE REPAIRING"));
		list.add(genItem("5364","DOOR SYSTEMS MECHANIC"));
		list.add(genItem("5479","DREDGING EQUIPMENT OPERATING"));
		list.add(genItem("5729","DRILL RIG OPERATING"));
		list.add(genItem("2854","ELECTRICAL EQUIPMENT REPAIRING"));
		list.add(genItem("2805","ELECTRICIAN"));
		list.add(genItem("5407","ELECTRIC POWER CONTROLLING"));
		list.add(genItem("4449","ELECTROLYTIC INTAGLIO PLATEMAKING"));
		list.add(genItem("5876","ELECTROMOTIVE EQUIPMENT MECHANIC"));
		list.add(genItem("2608","ELECTRONIC DIGITAL COMPUTER MECHANIC"));
		list.add(genItem("2606","ELECTRONIC INDUSTRIAL CONTROLS MECHANIC"));
		list.add(genItem("2610","ELECTRONIC INTEGRATED SYSTEMS MECHANIC"));
		list.add(genItem("2602","ELECTRONIC MEASUREMENT EQUIPMENT MECHANIC"));
		list.add(genItem("2604","ELECTRONICS MECHANIC"));
		list.add(genItem("3711","ELECTROPLATING"));
		list.add(genItem("5313","ELEVATOR MECHANIC"));
		list.add(genItem("5438","ELEVATOR OPERATING"));
		list.add(genItem("5716","ENGINEERING EQUIPMENT OPERATING"));
		list.add(genItem("3816","ENGRAVING"));
		list.add(genItem("7009","EQUIPMENT CLEANING"));
		list.add(genItem("4715","Exhibits Making/Modeling"));
		list.add(genItem("5471","EXHIBITS MAKING/MODELING"));
		list.add(genItem("6502","EXPLOSIVES OPERATING"));
		list.add(genItem("6517","EXPLOSIVES TEST OPERATING"));
		list.add(genItem("3105","FABRIC WORKING"));
		list.add(genItem("5002","FARMING"));
		list.add(genItem("9003","FILM ASSEMBLING AND REPAIRING"));
		list.add(genItem("4405","FILM ASSEMBLY-STRIPPING"));
		list.add(genItem("3702","FLAME/ARC CUTTING"));
		list.add(genItem("3609","FLOOR COVERING INSTALLING"));
		list.add(genItem("7408","FOOD SERVICE WORKING"));
		list.add(genItem("5704","FORK LIFT OPERATING"));
		list.add(genItem("4654","FORM BLOCK MAKING"));
		list.add(genItem("5413","FUEL DISTRIBUTION SYSTEM OPERATING"));
		list.add(genItem("4255","FUEL DISTRIBUTION SYSTEMS MECHANIC"));
		list.add(genItem("3741","FURNACE OPERATING"));
		list.add(genItem("5003","GARDENING"));
		list.add(genItem("5205","GAS AND RADIATION DETECTING"));
		list.add(genItem("5384","GASDYNAMIC FACILITY INSTALLING AND REPAIRING"));
		list.add(genItem("5433","GAS GENERATING PLANT OPERATING"));
		list.add(genItem("4737","GENERAL EQUIPMENT MECHANIC"));
		list.add(genItem("4741","GENERAL EQUIPMENT OPERATING"));
		list.add(genItem("4370","GLASSBLOWING"));
		list.add(genItem("3611","GLAZING"));
		list.add(genItem("4403","HAND COMPOSING"));
		list.add(genItem("6913","HAZARDOUS WASTE DISPOSING"));
		list.add(genItem("5309","HEATING AND BOILER PLANT EQUIPMENT MECHANIC"));
		list.add(genItem("3712","HEAT TREATING"));
		list.add(genItem("5803","HEAVY MOBILE EQUIPMENT MECHANIC"));
		list.add(genItem("2810","HIGH VOLTAGE ELECTRICIAN"));
		list.add(genItem("5403","INCINERATOR OPERATING"));
		list.add(genItem("5352","INDUSTRIAL EQUIPMENT MECHANIC"));
		list.add(genItem("5341","INDUSTRIAL FURNACE BUILDING AND REPAIRING"));
		list.add(genItem("5031","INSECTS PRODUCTION WORKING"));
		list.add(genItem("3314","INSTRUMENT MAKING"));
		list.add(genItem("3359","INSTRUMENT MECHANIC"));
		list.add(genItem("3610","INSULATING"));
		list.add(genItem("4450","INTAGLIO DIE AND PLATE FINISHING"));
		list.add(genItem("4454","INTAGLIO PRESS OPERATING"));
		list.add(genItem("5310","KITCHEN/BAKERY EQUIPMENT REPAIRING"));
		list.add(genItem("3515","LABORATORY SUPPORT WORKING"));
		list.add(genItem("3511","LABORATORY WORKING"));
		list.add(genItem("3502","LABORING"));
		list.add(genItem("5317","LAUNDRY AND DRY CLEANING EQUIPMENT REPAIRING"));
		list.add(genItem("7305","LAUNDRY MACHINE OPERATING"));
		list.add(genItem("7304","LAUNDRY WORKING"));
		list.add(genItem("3716","LEADBURNING"));
		list.add(genItem("4406","LETTERPRESS OPERATING"));
		list.add(genItem("8675","LIQUID FUEL ROCKET ENGINE MECHANIC"));
		list.add(genItem("5035","LIVESTOCK RANCHING/WRANGLING"));
		list.add(genItem("5426","LOCK AND DAM OPERATING"));
		list.add(genItem("5318","LOCK AND DAM REPAIRING"));
		list.add(genItem("4804","LOCKSMITHING"));
		list.add(genItem("5737","LOCOMOTIVE ENGINEERING"));
		list.add(genItem("5221","LOFTING"));
		list.add(genItem("3414","MACHINING"));
		list.add(genItem("4749","MAINTENANCE MECHANIC"));
		list.add(genItem("5334","MARINE MACHINERY MECHANIC"));
		list.add(genItem("3603","MASONRY"));
		list.add(genItem("6912","MATERIALS EXAMINING AND IDENTIFYING"));
		list.add(genItem("6910","MATERIALS EXPEDITING"));
		list.add(genItem("6907","MATERIALS HANDLING"));
		list.add(genItem("7407","MEATCUTTING"));
		list.add(genItem("4848","MECHANICAL PARTS REPAIRING"));
		list.add(genItem("4805","MEDICAL EQUIPMENT REPAIRING"));
		list.add(genItem("3802","METAL FORGING"));
		list.add(genItem("3869","METAL FORMING MACHINE OPERATING"));
		list.add(genItem("3707","METALIZING"));
		list.add(genItem("3735","METAL PHOTOTRANSFERRING"));
		list.add(genItem("3858","METAL TANK AND RADIATOR REPAIRING"));
		list.add(genItem("3872","METAL TUBE MAKING, INSTALLING, AND REPAIRING"));
		list.add(genItem("6511","MISSILE/TOXIC MATERIALS HANDLING"));
		list.add(genItem("3809","MOBILE EQUIPMENT METAL MECHANIC"));
		list.add(genItem("5806","MOBILE EQUIPMENT SERVICING"));
		list.add(genItem("4714","MODEL MAKING"));
		list.add(genItem("4373","MOLDING"));
		list.add(genItem("9004","MOTION PICTURE DEVELOPING/PRINTING MACHINE OPERATING"));
		list.add(genItem("3910","MOTION PICTURE PROJECTION"));
		list.add(genItem("5703","MOTOR VEHICLE OPERATING"));
		list.add(genItem("6505","MUNITIONS DESTROYING"));
		list.add(genItem("4413","NEGATIVE ENGRAVING"));
		list.add(genItem("3705","NONDESTRUCTIVE TESTING"));
		list.add(genItem("4806","OFFICE APPLIANCE REPAIRING"));
		list.add(genItem("4414","OFFSET PHOTOGRAPHY"));
		list.add(genItem("4417","OFFSET PRESS OPERATING"));
		list.add(genItem("5323","OILING AND GREASING"));
		list.add(genItem("4005","OPTICAL ELEMENT WORKING"));
		list.add(genItem("3306","OPTICAL INSTRUMENT REPAIRING"));
		list.add(genItem("3501","OPTICAL WORKER"));
		list.add(genItem("6641","ORDNANCE EQUIPMENT MECHANIC"));
		list.add(genItem("4845","ORTHOPEDIC APPLIANCE REPAIRING"));
		list.add(genItem("5440","PACKAGING MACHINE OPERATING"));
		list.add(genItem("7002","PACKING"));
		list.add(genItem("4102","PAINTING"));
		list.add(genItem("4103","PAPERHANGING"));
		list.add(genItem("5455","PAPER PULPING MACHINE OPERATING"));
		list.add(genItem("7010","PARACHUTE PACKING"));
		list.add(genItem("4616","PATTERNMAKING"));
		list.add(genItem("5026","PEST CONTROLLING"));
		list.add(genItem("4425","PHOTOENGRAVING"));
		list.add(genItem("5365","PHYSIOLOGICAL TRAINER MECHANIC"));
		list.add(genItem("4204","PIPEFITTING"));
		list.add(genItem("3605","PLASTERING"));
		list.add(genItem("4352","PLASTIC FABRICATING"));
		list.add(genItem("4351","PLASTIC MOLDING EQUIPMENT OPERATING"));
		list.add(genItem("4416","PLATEMAKING"));
		list.add(genItem("4206","PLUMBING"));
		list.add(genItem("8255","PNEUDRAULIC SYSTEMS MECHANIC"));
		list.add(genItem("5478","PORTABLE EQUIPMENT OPERATING"));
		list.add(genItem("5378","POWERED SUPPORT SYSTEMS MECHANIC"));
		list.add(genItem("4010","PRESCRIPTION EYEGLASS MAKING"));
		list.add(genItem("7006","PRESERVATION SERVICING"));
		list.add(genItem("7306","PRESSING"));
		list.add(genItem("5330","PRINTING EQUIPMENT REPAIRING"));
		list.add(genItem("5350","PRODUCTION MACHINERY MECHANIC"));
		list.add(genItem("4816","PROTECTIVE AND SAFETY EQUIPMENT FABRICATING AND REPAIRING"));
		list.add(genItem("4716","RAILROAD CAR REPAIRING"));
		list.add(genItem("5738","RAILROAD MAINTENANCE VEHICLE OPERATING"));
		list.add(genItem("3546","RAILROAD REPAIRING"));
		list.add(genItem("4745","RESEARCH LABORATORY MECHANIC"));
		list.add(genItem("5210","RIGGING"));
		list.add(genItem("5784","RIVERBOAT OPERATING"));
		list.add(genItem("5706","ROAD SWEEPER OPERATING"));
		list.add(genItem("3606","ROOFING"));
		list.add(genItem("4361","RUBBER EQUIPMENT REPAIRING"));
		list.add(genItem("4360","RUBBER PRODUCTS MOLDING"));
		list.add(genItem("5423","SANDBLASTING"));
		list.add(genItem("4447","SCULPTURAL ENGRAVING"));
		list.add(genItem("3111","SEWING MACHINE OPERATING"));
		list.add(genItem("3806","SHEET METAL MECHANIC"));
		list.add(genItem("3820","SHIPFITTING"));
		list.add(genItem("5782","SHIP OPERATING"));
		list.add(genItem("5220","SHIPWRIGHT"));
		list.add(genItem("3103","SHOE REPAIRING"));
		list.add(genItem("3769","SHOT PEENING MACHINE OPERATING"));
		list.add(genItem("4448","SIDEROGRAPHIC TRANSFERRING"));
		list.add(genItem("4104","SIGN PAINTING"));
		list.add(genItem("4419","SILK SCREEN MAKING AND PRINTING"));
		list.add(genItem("6610","SMALL ARMS REPAIRING"));
		list.add(genItem("5786","SMALL CRAFT OPERATING"));
		list.add(genItem("8610","SMALL ENGINE MECHANIC"));
		list.add(genItem("6566","SPECIAL WEAPONS SYSTEMS MECHANIC"));
		list.add(genItem("5419","STATIONARY ENGINE OPERATING"));
		list.add(genItem("4440","STEREOTYPE PLATEMAKING"));
		list.add(genItem("3543","STEVEDORING"));
		list.add(genItem("6914","STORE WORKING"));
		list.add(genItem("3807","STRUCTURAL/ORNAMENTAL IRON WORKING"));
		list.add(genItem("3506","SUMMER AID/STUDENT AID"));
		list.add(genItem("2502","TELECOMMUNICATIONS MECHANIC"));
		list.add(genItem("5439","TESTING EQUIPMENT OPERATING"));
		list.add(genItem("5235","TEST RANGE TRACKING"));
		list.add(genItem("5446","TEXTILE EQUIPMENT OPERATING"));
		list.add(genItem("3604","TILE SETTING"));
		list.add(genItem("4639","TIMBER WORKING"));
		list.add(genItem("4840","TOOL AND EQUIPMENT REPAIRING"));
		list.add(genItem("3417","TOOL GRINDING"));
		list.add(genItem("3416","TOOLMAKING"));
		list.add(genItem("6904","TOOLS AND PARTS ATTENDING"));
		list.add(genItem("5705","TRACTOR OPERATING"));
		list.add(genItem("3833","TRANSFER ENGRAVING"));
		list.add(genItem("5042","TREE TRIMMING AND REMOVING"));
		list.add(genItem("3106","UPHOLSTERING"));
		list.add(genItem("5406","UTILITY SYSTEMS OPERATING"));
		list.add(genItem("4742","UTILITY SYSTEMS REPAIRING OPERATING"));
		list.add(genItem("4820","VENDING MACHINE REPAIRING"));
		list.add(genItem("","WAGE GRADE OTHER"));
		list.add(genItem("7420","WAITER"));
		list.add(genItem("5408","WASTEWATER TREATMENT PLANT OPERATING"));
		list.add(genItem("5409","WATER TREATMENT PLANT OPERATING"));
		list.add(genItem("5424","WEIGHING MACHINE OPERATING"));
		list.add(genItem("3703","WELDING"));
		list.add(genItem("5335","WIND TUNNEL MECHANIC"));
		list.add(genItem("2504","WIRE COMMUNICATIONS CABLE SPLICING"));
		list.add(genItem("4605","WOOD CRAFTING"));
		list.add(genItem("4604","WOOD WORKING"));
	}

	private void loadWM(List<OptionListItem> list) {
			list.add(genItem("9924","ABLE SEAMAN"));
			list.add(genItem("9925","ABLE SEAMAN-MAINTENANCE"));
			list.add(genItem("9975","ASSISTANT COOK"));
			list.add(genItem("9915","ASSISTANT DAMAGE CONTROL OFFICER"));
			list.add(genItem("9983","ASSISTANT LAUNDRYMAN"));
			list.add(genItem("9949","ASSISTANT PLUMBER"));
			list.add(genItem("9994","ASSISTANT STOREKEEPER"));
			list.add(genItem("9992","ASSISTANT SUPPLY OFFICER"));
			list.add(genItem("9920","BOATSWAIN"));
			list.add(genItem("9923","BOATSWAINS MATE"));
			list.add(genItem("9921","CARPENTER"));
			list.add(genItem("9922","CARPENTER-MAINTENANCE"));
			list.add(genItem("9995","CHIEF, RADIO ELECTRONICS TECHNICIAN"));
			list.add(genItem("9971","CHIEF COOK"));
			list.add(genItem("9939","CHIEF ELECTRICIAN"));
			list.add(genItem("9931","CHIEF ENGINEER"));
			list.add(genItem("9903","CHIEF OFFICER CABLE"));
			list.add(genItem("9968","CHIEF STEWARD"));
			list.add(genItem("9976","COOK-BAKER"));
			list.add(genItem("9919","DAMAGE CONTROL ASSISTANT LEADER"));
			list.add(genItem("9918","DAMAGE CONTROL LEADER"));
			list.add(genItem("9929","DAMAGE CONTROLMAN"));
			list.add(genItem("9914","DAMAGE CONTROL OFFICER"));
			list.add(genItem("9951","DECK ENGINEER"));
			list.add(genItem("9952","DECK ENGINEER-MACHINIST"));
			list.add(genItem("9953","DECK ENGINEER-MECHANIC"));
			list.add(genItem("9917","DECK MIDSHIPMAN"));
			list.add(genItem("9990","DISBURSING OFFICER"));
			list.add(genItem("9940","ELECTRICIAN"));
			list.add(genItem("9941","ELECTRICIAN-MAINTENANCE"));
			list.add(genItem("9944","ELECTRONICS TECHNICIAN"));
			list.add(genItem("9956","ENGINEMAN"));
			list.add(genItem("9936","ENGINE MIDSHIPMAN"));
			list.add(genItem("9957","ENGINE UTILITYMAN"));
			list.add(genItem("9958","EVAPORATOR-UTILITYMAN"));
			list.add(genItem("9963","FIREMAN"));
			list.add(genItem("9964","FIREMAN-WATERTENDER"));
			list.add(genItem("9932","FIRST ASSISTANT ENGINEER"));
			list.add(genItem("9912","FIRST ASSISTANT RADIO ELECTRONICS OFFICER"));
			list.add(genItem("9910","FIRST ASSISTANT RADIO OFFICER"));
			list.add(genItem("9905","FIRST OFFICER"));
			list.add(genItem("9997","FIRST RADIO ELECTRONICS TECHNICIAN"));
			list.add(genItem("9981","GALLEYMAN"));
			list.add(genItem("9989","JUNIOR PURSER"));
			list.add(genItem("9993","JUNIOR SUPPLY OFFICER"));
			list.add(genItem("9982","LAUNDRYMAN"));
			list.add(genItem("9959","MACHINIST"));
			list.add(genItem("9902","MASTER"));
			list.add(genItem("9916","MASTER-MATE (FISHING VESSEL)"));
			list.add(genItem("9996","MEDICAL SERVICES OFFICER"));
			list.add(genItem("9984","MESSMAN"));
			list.add(genItem("9901","MISCELLANEOUS JOBS NOT COVERED BY SPECIFIC OCCUPAT"));
			list.add(genItem("9978","NIGHT COOK AND BAKER"));
			list.add(genItem("9960","OILER"));
			list.add(genItem("9961","OILER-DIESEL"));
			list.add(genItem("9928","ORDINARY SEAMAN"));
			list.add(genItem("ZZZZ","OTHER"));
			list.add(genItem("9948","PLUMBER"));
			list.add(genItem("9950","PLUMBER MACHINIST"));
			list.add(genItem("9955","PUMPMAN"));
			list.add(genItem("9988","PURSER"));
			list.add(genItem("9926","QUARTERMASTER"));
			list.add(genItem("9911","RADIO ELECTRONICS OFFICER"));
			list.add(genItem("9909","RADIO OFFICER"));
			list.add(genItem("9945","REFRIGERATION ENGINEER"));
			list.add(genItem("9962","REFRIGERATION OILER"));
			list.add(genItem("9913","RELIEF DECK OFFICER"));
			list.add(genItem("9935","RELIEF ENGINEER"));
			list.add(genItem("9927","SEAMAN-FISHERMAN"));
			list.add(genItem("9933","SECOND ASSISTANT ENGINEER"));
			list.add(genItem("9973","SECOND COOK"));
			list.add(genItem("9977","SECOND COOK-BAKER"));
			list.add(genItem("9942","SECOND ELECTRICIAN"));
			list.add(genItem("9906","SECOND OFFICER"));
			list.add(genItem("9999","SECOND RADIO ELECTRONICS TECHNICIAN"));
			list.add(genItem("9946","SECOND REFRIGERATION ENGINEER"));
			list.add(genItem("9908","SHIP'S COMMUNICATION OFFICER"));
			list.add(genItem("9904","SHIP PILOT"));
			list.add(genItem("9979","STEWARD-BAKER"));
			list.add(genItem("9972","STEWARD COOK"));
			list.add(genItem("9985","STEWARD-UTILITYMAN"));
			list.add(genItem("9991","SUPPLY OFFICER"));
			list.add(genItem("9934","THIRD ASSISTANT ENGINEER"));
			list.add(genItem("9974","THIRD COOK"));
			list.add(genItem("9943","THIRD ELECTRICIAN"));
			list.add(genItem("9907","THIRD OFFICER"));
			list.add(genItem("9980","THIRD PANTRYMAN"));
			list.add(genItem("9947","THIRD REFRIGERATION ENGINEER"));
			list.add(genItem("9969","THIRD STEWARD"));
			list.add(genItem("XXXX","UNKNOWN"));
			list.add(genItem("9954","UNLICENSED JUNIOR ENGINEER"));
			list.add(genItem("9965","WIPER"));
			list.add(genItem("9998","YEOMAN-STOREKEEPER"));
	}

	private void loadGS(List<OptionListItem> list) {
		list.add(genItem("0510","ACCOUNTING"));
		list.add(genItem("0525","ACCOUNTING TECHNICIAN"));
		list.add(genItem("1510","ACTUARY"));
		list.add(genItem("0399","ADMINISTRATION AND OFFICE SUPPORT STUDENT TRAINEE"));
		list.add(genItem("0341","ADMINISTRATIVE OFFICER"));
		list.add(genItem("0861","AEROSPACE ENGINEERING"));
		list.add(genItem("1981","AGRICULTURAL COMMODITY AID"));
		list.add(genItem("1980","AGRICULTURAL COMMODITY GRADING"));
		list.add(genItem("1850","AGRICULTURAL COMMODITY WAREHOUSE EXAMINING"));
		list.add(genItem("0890","AGRICULTURAL ENGINEERING"));
		list.add(genItem("0406","AGRICULTURAL EXTENSION"));
		list.add(genItem("1146","AGRICULTURAL MARKETING"));
		list.add(genItem("1147","AGRICULTURAL MARKET REPORTING"));
		list.add(genItem("1145","AGRICULTURAL PROGRAM SPECIALIST"));
		list.add(genItem("0471","AGRONOMY"));
		list.add(genItem("2181","AIRCRAFT OPERATION"));
		list.add(genItem("2185","AIRCREW TECHNICIAN"));
		list.add(genItem("2183","AIR NAVIGATION"));
		list.add(genItem("1815","AIR SAFETY INVESTIGATING"));
		list.add(genItem("2154","AIR TRAFFIC ASSISTANCE"));
		list.add(genItem("2152","AIR TRAFFIC CONTROL"));
		list.add(genItem("1854","ALCOHOL, TOBACCO AND FIREARMS INSPECTION"));
		list.add(genItem("0704","ANIMAL HEALTH TECHNICIAN"));
		list.add(genItem("0487","ANIMAL SCIENCE"));
		list.add(genItem("1171","APPRAISING"));
		list.add(genItem("0243","APPRENTICESHIP AND TRAINING"));
		list.add(genItem("0193","ARCHEOLOGY"));
		list.add(genItem("0808","ARCHITECTURE"));
		list.add(genItem("1421","ARCHIVES TECHNICIAN"));
		list.add(genItem("1420","ARCHIVIST"));
		list.add(genItem("1056","ART SPECIALIST"));
		list.add(genItem("1330","ASTRONOMY AND SPACE SCIENCE"));
		list.add(genItem("1071","AUDIOVISUAL PRODUCTION"));
		list.add(genItem("0511","AUDITING"));
		list.add(genItem("0625","AUTOPSY ASSISTANT"));
		list.add(genItem("1825","AVIATION SAFETY"));
		list.add(genItem("0499","BIOLOGICAL SCIENCE STUDENT TRAINEE"));
		list.add(genItem("0404","BIOLOGICAL SCIENCE TECHNICIAN"));
		list.add(genItem("0858","BIOMEDICAL ENGINEERING"));
		list.add(genItem("0011","BOND SALES PROMOTION"));
		list.add(genItem("1896","BORDER PATROL AGENT"));
		list.add(genItem("0430","BOTANY"));
		list.add(genItem("0560","BUDGET ANALYSIS"));
		list.add(genItem("0561","BUDGET CLERICAL AND ASSISTANCE"));
		list.add(genItem("1176","BUILDING MANAGEMENT"));
		list.add(genItem("1199","BUSINESS AND INDUSTRY STUDENT TRAINEE"));
		list.add(genItem("2144","CARGO SCHEDULING"));
		list.add(genItem("1371","CARTOGRAPHIC TECHNICIAN"));
		list.add(genItem("1370","CARTOGRAPHY"));
		list.add(genItem("0530","CASH PROCESSING"));
		list.add(genItem("1630","CEMETERY ADMINISTRATION"));
		list.add(genItem("0892","CERAMIC ENGINEERING"));
		list.add(genItem("0060","CHAPLAIN"));
		list.add(genItem("0893","CHEMICAL ENGINEERING"));
		list.add(genItem("1320","CHEMISTRY"));
		list.add(genItem("0810","CIVIL ENGINEERING"));
		list.add(genItem("0544","CIVILIAN PAY"));
		list.add(genItem("0160","CIVIL RIGHTS ANALYSIS"));
		list.add(genItem("0998","CLAIMS ASSISTANCE AND EXAMINING"));
		list.add(genItem("0945","CLERK OF COURT"));
		list.add(genItem("0312","CLERK-STENOGRAPHER AND REPORTER"));
		list.add(genItem("0322","CLERK-TYPIST"));
		list.add(genItem("0319","CLOSED MICROPHONE REPORTING"));
		list.add(genItem("0062","CLOTHING DESIGN"));
		list.add(genItem("0357","CODING"));
		list.add(genItem("1144","COMMISSARY STORE MANAGEMENT"));
		list.add(genItem("0394","COMMUNICATIONS CLERICAL"));
		list.add(genItem("0020","COMMUNITY PLANNING"));
		list.add(genItem("0021","COMMUNITY PLANNING TECHNICIAN"));
		list.add(genItem("1802","COMPLIANCE INSPECTION AND SUPPORT"));
		list.add(genItem("0335","COMPUTER CLERK AND ASSISTANT"));
		list.add(genItem("0854","COMPUTER ENGINEERING"));
		list.add(genItem("0332","COMPUTER OPERATION"));
		list.add(genItem("1550","COMPUTER SCIENCE"));
		list.add(genItem("0828","CONSTRUCTION ANALYST"));
		list.add(genItem("0809","CONSTRUCTION CONTROL"));
		list.add(genItem("0696","CONSUMER SAFETY"));
		list.add(genItem("1862","CONSUMER SAFETY INSPECTION"));
		list.add(genItem("0962","CONTACT REPRESENTATIVE"));
		list.add(genItem("1102","CONTRACTING"));
		list.add(genItem("1210","COPYRIGHT"));
		list.add(genItem("1299","COPYRIGHT AND PATENT STUDENT TRAINEE"));
		list.add(genItem("1211","COPYRIGHT TECHNICIAN"));
		list.add(genItem("0006","CORRECTIONAL INSTITUTION ADMINISTRATION"));
		list.add(genItem("0007","CORRECTIONAL OFFICER"));
		list.add(genItem("0635","CORRECTIVE THERAPIST"));
		list.add(genItem("0309","CORRESPONDENCE CLERK"));
		list.add(genItem("1811","CRIMINAL INVESTIGATING"));
		list.add(genItem("1161","CROP INSURANCE ADMINISTRATION"));
		list.add(genItem("1162","CROP INSURANCE UNDERWRITING"));
		list.add(genItem("1541","CRYPTANALYSIS"));
		list.add(genItem("1540","CRYPTOGRAPHY"));
		list.add(genItem("1897","CUSTOMS AID"));
		list.add(genItem("1894","CUSTOMS ENTRY AND LIQUIDATING"));
		list.add(genItem("1890","CUSTOMS INSPECTION"));
		list.add(genItem("1884","CUSTOMS PATROL OFFICER"));
		list.add(genItem("0356","DATA TRANSCRIBER"));
		list.add(genItem("0681","DENTAL ASSISTANT"));
		list.add(genItem("0682","DENTAL HYGIENE"));
		list.add(genItem("0683","DENTAL LABORATORY AID AND TECHNICIAN"));
		list.add(genItem("0680","DENTAL OFFICER"));
		list.add(genItem("1226","DESIGN PATENT EXAMINING"));
		list.add(genItem("0647","DIAGNOSTIC RADIOLOGIC TECHNOLOGIST"));
		list.add(genItem("0630","DIETITIAN AND NUTRITIONIST"));
		list.add(genItem("2151","DISPATCHING"));
		list.add(genItem("2030","DISTRIBUTION FACILITIES AND STORAGE MANAGEMENT"));
		list.add(genItem("1397","DOCUMENT ANALYSIS"));
		list.add(genItem("0408","ECOLOGY"));
		list.add(genItem("0119","ECONOMICS ASSISTANT"));
		list.add(genItem("0110","ECONOMIST"));
		list.add(genItem("1087","EDITORIAL ASSISTANCE"));
		list.add(genItem("0639","EDUCATIONAL THERAPIST"));
		list.add(genItem("1702","EDUCATION AND TRAINING TECHNICIAN"));
		list.add(genItem("1710","EDUCATION AND VOCATIONAL TRAINING"));
		list.add(genItem("1720","EDUCATION PROGRAM"));
		list.add(genItem("1730","EDUCATION RESEARCH"));
		list.add(genItem("1740","EDUCATION SERVICES"));
		list.add(genItem("1799","EDUCATION STUDENT TRAINEE"));
		list.add(genItem("0850","ELECTRICAL ENGINEERING"));
		list.add(genItem("0855","ELECTRONICS ENGINEERING"));
		list.add(genItem("0856","ELECTRONICS TECHNICIAN"));
		list.add(genItem("0899","ENGINEERING AND ARCHITECTURE STUDENT TRAINEE"));
		list.add(genItem("0818","ENGINEERING DRAFTING"));
		list.add(genItem("0802","ENGINEERING TECHNICIAN"));
		list.add(genItem("0414","ENTOMOLOGY"));
		list.add(genItem("0819","ENVIRONMENTAL ENGINEERING"));
		list.add(genItem("0698","ENVIRONMENTAL HEALTH TECHNICIAN"));
		list.add(genItem("0029","ENVIRONMENTAL PROTECTION ASSISTANT"));
		list.add(genItem("0028","ENVIRONMENTAL PROTECTION SPECIALIST"));
		list.add(genItem("0260","EQUAL EMPLOYMENT OPPORTUNITY"));
		list.add(genItem("0361","EQUAL OPPORTUNITY ASSISTANCE"));
		list.add(genItem("0360","EQUAL OPPORTUNITY COMPLIANCE"));
		list.add(genItem("1699","EQUIPMENT AND FACILITIES MANAGEMENT STUDENT TRAINEE"));
		list.add(genItem("0350","EQUIPMENT OPERATOR"));
		list.add(genItem("1670","EQUIPMENT SPECIALIST"));
		list.add(genItem("0920","ESTATE TAX EXAMINING"));
		list.add(genItem("1010","EXHIBITS SPECIALIST"));
		list.add(genItem("1640","FACILITY MANAGEMENT"));
		list.add(genItem("0501","FINANCIAL ADMINISTRATION AND PROGRAM"));
		list.add(genItem("1160","FINANCIAL ANALYSIS"));
		list.add(genItem("0503","FINANCIAL CLERICAL AND ASSISTANCE"));
		list.add(genItem("0505","FINANCIAL MANAGEMENT"));
		list.add(genItem("0599","FINANCIAL MANAGEMENT STUDENT TRAINEE"));
		list.add(genItem("0072","FINGERPRINT IDENTIFICATION"));
		list.add(genItem("0081","FIRE PROTECTION AND PREVENTION"));
		list.add(genItem("0804","FIRE PROTECTION ENGINEERING"));
		list.add(genItem("0482","FISHERY BIOLOGY"));
		list.add(genItem("1863","FOOD INSPECTION"));
		list.add(genItem("1382","FOOD TECHNOLOGY"));
		list.add(genItem("0130","FOREIGN AFFAIRS"));
		list.add(genItem("0135","FOREIGN AGRICULTURAL AFFAIRS"));
		list.add(genItem("0095","FOREIGN LAW SPECIALIST"));
		list.add(genItem("1380","FOREST PRODUCTS TECHNOLOGY"));
		list.add(genItem("0460","FORESTRY"));
		list.add(genItem("0462","FORESTRY TECHNICIAN"));
		list.add(genItem("2131","FREIGHT RATE"));
		list.add(genItem("1812","GAME LAW ENFORCEMENT"));
		list.add(genItem("0190","GENERAL ANTHROPOLOGY"));
		list.add(genItem("1001","GENERAL ARTS AND INFORMATION"));
		list.add(genItem("0905","GENERAL ATTORNEY"));
		list.add(genItem("0401","GENERAL BIOLOGICAL SCIENCE"));
		list.add(genItem("1101","GENERAL BUSINESS AND INDUSTRY"));
		list.add(genItem("1701","GENERAL EDUCATION AND TRAINING"));
		list.add(genItem("0801","GENERAL ENGINEERING"));
		list.add(genItem("1601","GENERAL FACILITIES AND EQUIPMENT"));
		list.add(genItem("0480","GENERAL FISH AND WILDLIFE ADMINISTRATION"));
		list.add(genItem("0601","GENERAL HEALTH SCIENCE"));
		list.add(genItem("1801","GENERAL INSPECTION, INVESTIGATION, AND COMPLIANCE"));
		list.add(genItem("1810","GENERAL INVESTIGATING"));
		list.add(genItem("0901","GENERAL LEGAL AND KINDRED ADMINISTRATION"));
		list.add(genItem("1301","GENERAL PHYSICAL SCIENCE"));
		list.add(genItem("0099","GENERAL STUDENT TRAINEE"));
		list.add(genItem("2001","GENERAL SUPPLY"));
		list.add(genItem("0392","GENERAL TELECOMMUNICATIONS"));
		list.add(genItem("0440","GENETICS"));
		list.add(genItem("1372","GEODESY"));
		list.add(genItem("1374","GEODETIC TECHNICIAN"));
		list.add(genItem("0150","GEOGRAPHY"));
		list.add(genItem("1350","GEOLOGY"));
		list.add(genItem("1313","GEOPHYSICS"));
		list.add(genItem("","GS OTHER"));
		list.add(genItem("0090","GUIDE"));
		list.add(genItem("0640","HEALTH AID AND TECHNICIAN"));
		list.add(genItem("0107","HEALTH INSURANCE ADMINISTRATION"));
		list.add(genItem("1306","HEALTH PHYSICS"));
		list.add(genItem("0670","HEALTH SYSTEM ADMINISTRATION"));
		list.add(genItem("0671","HEALTH SYSTEM SPECIALIST"));
		list.add(genItem("0930","HEARINGS AND APPEALS"));
		list.add(genItem("2125","HIGHWAY SAFETY"));
		list.add(genItem("0170","HISTORY"));
		list.add(genItem("0493","HOME ECONOMICS"));
		list.add(genItem("0437","HORTICULTURE"));
		list.add(genItem("0673","HOSPITAL HOUSEKEEPING MANAGEMENT"));
		list.add(genItem("1173","HOUSING MANAGEMENT"));
		list.add(genItem("0203","HUMAN RESOURCES ASSISTANCE"));
		list.add(genItem("0201","HUMAN RESOURCES MANAGEMENT"));
		list.add(genItem("0299","HUMAN RESOURCES MANAGEMENT STUDENT TRAINEE"));
		list.add(genItem("1316","HYDROLOGIC TECHNICIAN"));
		list.add(genItem("1315","HYDROLOGY"));
		list.add(genItem("1020","ILLUSTRATING"));
		list.add(genItem("1816","IMMIGRATION INSPECTION"));
		list.add(genItem("1889","IMPORT SPECIALIST"));
		list.add(genItem("0896","INDUSTRIAL ENGINEERING"));
		list.add(genItem("0895","INDUSTRIAL ENGINEERING TECHNICIAN"));
		list.add(genItem("0690","INDUSTRIAL HYGIENE"));
		list.add(genItem("1103","INDUSTRIAL PROPERTY MANAGEMENT"));
		list.add(genItem("1150","INDUSTRIAL SPECIALIST"));
		list.add(genItem("1099","INFORMATION AND ARTS STUDENT TRAINEE"));
		list.add(genItem("0304","INFORMATION RECEPTIONIST"));
		list.add(genItem("2210","INFORMATION TECHNOLOGY MANAGEMENT"));
		list.add(genItem("2299","INFORMATION TECHNOLOGY STUDENT TRAINEE"));
		list.add(genItem("1750","INSTRUCTIONAL SYSTEMS"));
		list.add(genItem("0593","INSURANCE ACCOUNTS"));
		list.add(genItem("1163","INSURANCE EXAMINING"));
		list.add(genItem("0132","INTELLIGENCE"));
		list.add(genItem("0134","INTELLIGENCE AID AND CLERK"));
		list.add(genItem("1008","INTERIOR DESIGN"));
		list.add(genItem("0512","INTERNAL REVENUE AGENT"));
		list.add(genItem("1169","INTERNAL REVENUE OFFICER"));
		list.add(genItem("0136","INTERNATIONAL COOPERATION"));
		list.add(genItem("0131","INTERNATIONAL RELATIONS"));
		list.add(genItem("2010","INVENTORY MANAGEMENT"));
		list.add(genItem("1899","INVESTIGATION STUDENT TRAINEE"));
		list.add(genItem("0459","IRRIGATION SYSTEM OPERATION"));
		list.add(genItem("0244","LABOR MANAGEMENT RELATIONS EXAMINING"));
		list.add(genItem("0965","LAND LAW EXAMINING"));
		list.add(genItem("0807","LANDSCAPE ARCHITECTURE"));
		list.add(genItem("1373","LAND SURVEYING"));
		list.add(genItem("1046","LANGUAGE CLERICAL"));
		list.add(genItem("1040","LANGUAGE SPECIALIST"));
		list.add(genItem("1658","LAUNDRY AND DRY CLEANING PLANT MANAGEMENT"));
		list.add(genItem("0904","LAW CLERK"));
		list.add(genItem("0986","LEGAL ASSISTANCE"));
		list.add(genItem("0963","LEGAL INSTRUMENTS EXAMINING"));
		list.add(genItem("0999","LEGAL OCCUPATIONS STUDENT TRAINEE"));
		list.add(genItem("1410","LIBRARIAN"));
		list.add(genItem("1499","LIBRARY AND ARCHIVES STUDENT TRAINEE"));
		list.add(genItem("1411","LIBRARY TECHNICIAN"));
		list.add(genItem("1165","LOAN SPECIALIST"));
		list.add(genItem("0346","LOGISTICS MANAGEMENT"));
		list.add(genItem("0305","MAIL AND FILE"));
		list.add(genItem("0343","MANAGEMENT AND PROGRAM ANALYSIS"));
		list.add(genItem("0344","MANAGEMENT AND PROGRAM CLERICAL AND ASSISTANCE"));
		list.add(genItem("0142","MANPOWER DEVELOPMENT"));
		list.add(genItem("0140","MANPOWER RESEARCH AND ANALYSIS"));
		list.add(genItem("0637","MANUAL ARTS THERAPIST"));
		list.add(genItem("2161","MARINE CARGO"));
		list.add(genItem("0806","MATERIALS ENGINEERING"));
		list.add(genItem("1529","MATHEMATICAL STATISTICIAN"));
		list.add(genItem("1520","MATHEMATICS"));
		list.add(genItem("1599","MATHEMATICS AND STATISTICS STUDENT TRAINEE"));
		list.add(genItem("1521","MATHEMATICS TECHNICIAN"));
		list.add(genItem("0830","MECHANICAL ENGINEERING"));
		list.add(genItem("0241","MEDIATION"));
		list.add(genItem("0699","MEDICAL AND HEALTH STUDENT TRAINEE"));
		list.add(genItem("0649","MEDICAL INSTRUMENT TECHNICIAN"));
		list.add(genItem("0602","MEDICAL OFFICER"));
		list.add(genItem("0669","MEDICAL RECORDS ADMINISTRATION"));
		list.add(genItem("0675","MEDICAL RECORDS TECHNICIAN"));
		list.add(genItem("0622","MEDICAL SUPPLY AIDE AND TECHNICIAN"));
		list.add(genItem("0679","MEDICAL SUPPORT ASSISTANCE"));
		list.add(genItem("0650","MEDICAL TECHNICAL ASSISTANT"));
		list.add(genItem("0645","MEDICAL TECHNICIAN"));
		list.add(genItem("0644","MEDICAL TECHNOLOGIST"));
		list.add(genItem("0302","MESSENGER"));
		list.add(genItem("1321","METALLURGY"));
		list.add(genItem("1341","METEOROLOGICAL TECHNICIAN"));
		list.add(genItem("1340","METEOROLOGY"));
		list.add(genItem("0403","MICROBIOLOGY"));
		list.add(genItem("0545","MILITARY PAY"));
		list.add(genItem("1822","MINE SAFETY AND HEALTH"));
		list.add(genItem("0880","MINING ENGINEERING"));
		list.add(genItem("0301","MISCELLANEOUS ADMINISTRATION AND PROGRAM"));
		list.add(genItem("0303","MISCELLANEOUS CLERK AND ASSISTANT"));
		list.add(genItem("2123","MOTOR CARRIER SAFETY"));
		list.add(genItem("1015","MUSEUM CURATOR"));
		list.add(genItem("1016","MUSEUM SPECIALIST AND TECHNICIAN"));
		list.add(genItem("1051","MUSIC SPECIALIST"));
		list.add(genItem("0871","NAVAL ARCHITECTURE"));
		list.add(genItem("1361","NAVIGATIONAL INFORMATION"));
		list.add(genItem("0840","NUCLEAR ENGINEERING"));
		list.add(genItem("0084","NUCLEAR MATERIALS COURIER"));
		list.add(genItem("0642","NUCLEAR MEDICINE TECHNICIAN"));
		list.add(genItem("0610","NURSE"));
		list.add(genItem("0621","NURSING ASSISTANT"));
		list.add(genItem("0631","OCCUPATIONAL THERAPIST"));
		list.add(genItem("1360","OCEANOGRAPHY"));
		list.add(genItem("0326","OFFICE AUTOMATION CLERICAL AND ASSISTANCE"));
		list.add(genItem("1021","OFFICE DRAFTING"));
		list.add(genItem("1515","OPERATIONS RESEARCH"));
		list.add(genItem("0662","OPTOMETRIST"));
		list.add(genItem("0667","ORTHOTIST AND PROSTHETIST"));
		list.add(genItem("0023","OUTDOOR RECREATION PLANNING"));
		list.add(genItem("2032","PACKAGING"));
		list.add(genItem("0950","PARALEGAL SPECIALIST"));
		list.add(genItem("0025","PARK RANGER"));
		list.add(genItem("0967","PASSPORT AND VISA EXAMINING"));
		list.add(genItem("1220","PATENT ADMINISTRATION"));
		list.add(genItem("1221","PATENT ADVISOR"));
		list.add(genItem("1222","PATENT ATTORNEY"));
		list.add(genItem("1223","PATENT CLASSIFYING"));
		list.add(genItem("1224","PATENT EXAMINING"));
		list.add(genItem("1202","PATENT TECHNICIAN"));
		list.add(genItem("0646","PATHOLOGY TECHNICIAN"));
		list.add(genItem("0958","PENSION LAW SPECIALIST"));
		list.add(genItem("0881","PETROLEUM ENGINEERING"));
		list.add(genItem("0660","PHARMACIST"));
		list.add(genItem("0405","PHARMACOLOGY"));
		list.add(genItem("0661","PHARMACY TECHNICIAN"));
		list.add(genItem("1386","PHOTOGRAPHIC TECHNOLOGY"));
		list.add(genItem("1060","PHOTOGRAPHY"));
		list.add(genItem("1399","PHYSICAL SCIENCE STUDENT TRAINEE"));
		list.add(genItem("1311","PHYSICAL SCIENCE TECHNICIAN"));
		list.add(genItem("0633","PHYSICAL THERAPIST"));
		list.add(genItem("0603","PHYSICIANS ASSISTANT"));
		list.add(genItem("1310","PHYSICS"));
		list.add(genItem("0413","PHYSIOLOGY"));
		list.add(genItem("0434","PLANT PATHOLOGY"));
		list.add(genItem("0435","PLANT PHYSIOLOGY"));
		list.add(genItem("0436","PLANT PROTECTION AND QUARANTINE"));
		list.add(genItem("0421","PLANT PROTECTION TECHNICIAN"));
		list.add(genItem("0668","PODIATRIST"));
		list.add(genItem("0083","POLICE"));
		list.add(genItem("0620","PRACTICAL NURSE"));
		list.add(genItem("0351","PRINTING CLERICAL"));
		list.add(genItem("1654","PRINTING MANAGEMENT"));
		list.add(genItem("1106","PROCUREMENT CLERICAL AND TECHNICIAN"));
		list.add(genItem("1152","PRODUCTION CONTROL"));
		list.add(genItem("0340","PROGRAM MANAGEMENT"));
		list.add(genItem("1104","PROPERTY DISPOSAL"));
		list.add(genItem("1107","PROPERTY DISPOSAL CLERICAL AND TECHNICIAN"));
		list.add(genItem("0672","PROSTHETIC REPRESENTATIVE"));
		list.add(genItem("0180","PSYCHOLOGY"));
		list.add(genItem("0181","PSYCHOLOGY AID AND TECHNICIAN"));
		list.add(genItem("1035","PUBLIC AFFAIRS"));
		list.add(genItem("1725","PUBLIC HEALTH EDUCATOR"));
		list.add(genItem("0685","PUBLIC HEALTH PROGRAM SPECIALIST"));
		list.add(genItem("1864","PUBLIC HEALTH QUARANTINE INSPECTION"));
		list.add(genItem("1130","PUBLIC UTILITIES SPECIALIST"));
		list.add(genItem("1105","PURCHASING"));
		list.add(genItem("1910","QUALITY ASSURANCE"));
		list.add(genItem("1999","QUALITY INSPECTION STUDENT TRAINEE"));
		list.add(genItem("0993","RAILROAD RETIREMENT CLAIMS EXAMINING"));
		list.add(genItem("2121","RAILROAD SAFETY"));
		list.add(genItem("0454","RANGELAND MANAGEMENT"));
		list.add(genItem("0455","RANGE TECHNICIAN"));
		list.add(genItem("1170","REALTY"));
		list.add(genItem("0638","RECREATION/CREATIVE ARTS THERAPIST"));
		list.add(genItem("0189","RECREATION AID AND ASSISTANT"));
		list.add(genItem("0188","RECREATION SPECIALIST"));
		list.add(genItem("0636","REHABILITATION THERAPY ASSISTANT"));
		list.add(genItem("0651","RESPIRATORY THERAPIST"));
		list.add(genItem("0664","RESTORATION TECHNICIAN"));
		list.add(genItem("0018","SAFETY AND OCCUPATIONAL HEALTH MANAGEMENT"));
		list.add(genItem("0803","SAFETY ENGINEERING"));
		list.add(genItem("0019","SAFETY TECHNICIAN"));
		list.add(genItem("2091","SALES STORE CLERICAL"));
		list.add(genItem("0688","SANITARIAN"));
		list.add(genItem("0318","SECRETARY"));
		list.add(genItem("1831","SECURITIES COMPLIANCE EXAMINING"));
		list.add(genItem("0080","SECURITY ADMINISTRATION"));
		list.add(genItem("0086","SECURITY CLERICAL AND ASSISTANCE"));
		list.add(genItem("0085","SECURITY GUARD"));
		list.add(genItem("0873","SHIP SURVEYING"));
		list.add(genItem("0105","SOCIAL INSURANCE ADMINISTRATION"));
		list.add(genItem("0101","SOCIAL SCIENCE"));
		list.add(genItem("0102","SOCIAL SCIENCE AID AND TECHNICIAN"));
		list.add(genItem("0199","SOCIAL SCIENCE STUDENT TRAINEE"));
		list.add(genItem("0187","SOCIAL SERVICES"));
		list.add(genItem("0186","SOCIAL SERVICES AID AND ASSISTANT"));
		list.add(genItem("0185","SOCIAL WORK"));
		list.add(genItem("0184","SOCIOLOGY"));
		list.add(genItem("0457","SOIL CONSERVATION"));
		list.add(genItem("0458","SOIL CONSERVATION TECHNICIAN"));
		list.add(genItem("0470","SOIL SCIENCE"));
		list.add(genItem("0665","SPEECH PATHOLOGY AND AUDIOLOGY"));
		list.add(genItem("0030","SPORTS SPECIALIST"));
		list.add(genItem("1531","STATISTICAL ASSISTANT"));
		list.add(genItem("1530","STATISTICIAN"));
		list.add(genItem("1667","STEWARD"));
		list.add(genItem("2050","SUPPLY CATALOGING"));
		list.add(genItem("2005","SUPPLY CLERICAL AND TECHNICIAN"));
		list.add(genItem("2003","SUPPLY PROGRAM MANAGEMENT"));
		list.add(genItem("2099","SUPPLY STUDENT TRAINEE"));
		list.add(genItem("0342","SUPPORT SERVICES ADMINISTRATION"));
		list.add(genItem("0817","SURVEYING TECHNICIAN"));
		list.add(genItem("0592","TAX EXAMINING"));
		list.add(genItem("0987","TAX LAW SPECIALIST"));
		list.add(genItem("0526","TAX SPECIALIST"));
		list.add(genItem("1412","TECHNICAL INFORMATION SERVICES"));
		list.add(genItem("1083","TECHNICAL WRITING AND EDITING"));
		list.add(genItem("0391","TELECOMMUNICATIONS"));
		list.add(genItem("0390","TELECOMMUNICATIONS PROCESSING"));
		list.add(genItem("2502","TELEPHONE MECHANIC"));
		list.add(genItem("0382","TELEPHONE OPERATING"));
		list.add(genItem("1384","TEXTILE TECHNOLOGY"));
		list.add(genItem("1054","THEATER SPECIALIST"));
		list.add(genItem("0648","THERAPEUTIC RADIOLOGIC TECHNOLOGIST"));
		list.add(genItem("0415","TOXICOLOGY"));
		list.add(genItem("1140","TRADE SPECIALIST"));
		list.add(genItem("2130","TRAFFIC MANAGEMENT"));
		list.add(genItem("1712","TRAINING INSTRUCTION"));
		list.add(genItem("2102","TRANSPORTATION CLERK AND ASSISTANT"));
		list.add(genItem("2110","TRANSPORTATION INDUSTRY ANALYSIS"));
		list.add(genItem("2135","TRANSPORTATION LOSS AND DAMAGE CLAIMS EXAMINING"));
		list.add(genItem("2150","TRANSPORTATION OPERATIONS"));
		list.add(genItem("2101","TRANSPORTATION SPECIALIST"));
		list.add(genItem("2199","TRANSPORTATION STUDENT TRAINEE"));
		list.add(genItem("0106","UNEMPLOYMENT INSURANCE"));
		list.add(genItem("0082","UNITED STATES MARSHAL"));
		list.add(genItem("0996","VETERANS CLAIMS EXAMINING"));
		list.add(genItem("0701","VETERINARY MEDICAL SCIENCE"));
		list.add(genItem("0799","VETERINARY STUDENT TRAINEE"));
		list.add(genItem("1084","VISUAL INFORMATION"));
		list.add(genItem("1715","VOCATIONAL REHABILITATION"));
		list.add(genItem("0540","VOUCHER EXAMINING"));
		list.add(genItem("0249","WAGE AND HOUR COMPLIANCE"));
		list.add(genItem("0894","WELDING ENGINEERING"));
		list.add(genItem("0486","WILDLIFE BIOLOGY"));
		list.add(genItem("0485","WILDLIFE REFUGE MANAGEMENT"));
		list.add(genItem("0991","WORKERS COMPENSATION CLAIMS EXAMINING"));
		list.add(genItem("0313","WORK UNIT SUPERVISING"));
		list.add(genItem("1082","WRITING AND EDITING"));
		list.add(genItem("0410","ZOOLOGY"));
	}
}