/**
 * 
 */
package org.surreal.lobster.sharedcore.constants;

/**
 * @author robert.a.dyer
 *
 */
public enum UrlToken {
	AFLOAT,
	AFLOAT_INITIAL_NOTIFICATION,
	AVIATION,
	AVIATION_INITIAL_NOTIFICATION,
	DJRS,
	DJRS_DIVE_SUMMARY_URL,
	DRAFT_PDF_URL,
	EMAIL_SERVICE_URL,
	HAZARD_WEB,
	INTL_NTFCN_PDF_URL,
	JASPER,
	LANDING_PAGE,
	LEGACY_ESAMS_IMPORT,
	LEGACY_INITIAL_NOTIFICATION,
	LEGACY_REPORT,
	MVRS,
	MVRS_INITIAL_NOTIFICATION,
//	NTFCN_PDF_URL,
	SHORE_GROUND,
	SHORE_GROUND_INITIAL_NOTIFICATION,
	SPARC,
	SUBSYSTEM_PICKER_URL,
	WESS,
	WESS_COLLECTIVE,	
	WESS_JBOSS5_HOST_URL;
}
